### ISSUE TITLE
Redundant/Duplicate code

### ISSUE THREAD

**Issue by joh-klein** [Marko-M/Inchoo_SocialConnect#27]
This looks (and is) a little redundant …

https://github.com/Marko-M/Inchoo_SocialConnect/blob/master/app/code/community/Inchoo/SocialConnect/Helper/Google.php#L129

**Comment by Marko-M** [comment]
Hi @joh-klein,
yes, you're totally right. There was a lot of copy/pasting due to similarities between authentication providers, and this one obviously went wrong. It will be fixed as soon as possible, but pull request to develop branch from community would be much appreciated and would get this addressed faster. Also, these kind of things could really be refactored to reduce redundancy, something I have in the long term plans for Social Connect.

Thanks for pointing this out,
Regards

**Comment by joh-klein** [comment]
Yes, refactoring to DRY up the code would certainly make things more readable. :)

**Comment by Marko-M** [comment]
Fixed in develop, therefore close.
