### ISSUE TITLE
Can not login with google account

### ISSUE THREAD

**Issue by pushpendra07** [Marko-M/Inchoo_SocialConnect#54]
Hi,

I am trying to login with google account but in the end of process, it's show error "Unspecified OAuth error occurred". How can I solve this isssue.

**Comment by WEBXARC** [comment]
Same here

**Comment by lukos** [comment]
This means any of the http requests has returned a 400 or 401 error. To debug this, enable Magento logging since the response code and body are logged using Mage::log. It is always possible that Google have made some breaking change but more likely that you have a malformed client id or secret or haven't quite copied it correctly.

Magento comes with a built-in logging facility which can be enabled and configured in the back-end under System > Configuration > Developer
