### ISSUE TITLE
Facebook login after create account through FB 500 error.

### ISSUE THREAD

**Issue by Daniel304** [Marko-M/Inchoo_SocialConnect#63]
Hi I am using magento 1.9.2.4 with this plugin. 
I created a new user with facebook using this extension.
After this i am trying to login to the account with the facebook login button. It will redirect to "My account" but when clicking on anything it will log out immediatly.. trying to relogin will give an 500 error. The log says:
2016-07-14T14:07:49+00:00 ERR (3): Recoverable Error: Argument 1 passed to Mage_Sales_Model_Quote::setCustomer() must be an instance of Mage_Customer_Model_Customer, null given, called in /export/www/www.brickfever.nl/app/code/core/Mage/Checkout/Model/Session.php on line 166 and defined  in /export/www/www.brickfever.nl/app/code/core/Mage/Sales/Model/Quote.php on line 453

You can test this on: www.brickfever.nl

**Comment by Daniel304** [comment]
I found it has something to do with the account being saved as "not confirmed" if I set this account to be confirmed manually the account works

**Comment by Marko-M** [comment]
@Daniel304 I can't reproduce on a clean Magento 1.9.2.4 installation with SocialConnect v0.3.8. Since brickfever.nl has dozen extensions - each on its own or in combination with SocialConnect could be causing this issue for you.

You can either find the culprit and write details here for reference or opt for [commercial support](http://www.techytalk.info/contact/).

Regards,
Marko

**Comment by Daniel304** [comment]
Adding the following in the Helper/Facebook.php fixed my issue:

        $customer->setConfirmation(null);
        $customer->save();

        $customer->sendNewAccountEmail('confirmed', '', Mage::app()->getStore()->getId());

        **$customer->setConfirmation(null)->save();**
        Mage::getSingleton('customer/session')->setCustomerAsLoggedIn($customer);
